import { Template } from 'meteor/templating';

Template.bookPreview.helpers({
    days () {
        // Add autogenerated days data
        return [1,2,3];
    },
    months () {
        // Add autogenerated month data + current month set cheched
        return [{
            value: 'Февраль',
            checked: ''
        },
            {
                value: 'Март',
                checked: 'selected'
            }];
    },
    years () {
        // Add autogenerated year data + current year set cheched
        return [{
            value: 2016,
            checked: null
        },{
            value: 2017,
            checked: 'selected'
        },
            {
                value: 2018,
                checked: null
            }];
    }
})